### ISSUE TITLE
contribute debugging configuration to allow easy creation of debugging launchers for orogen components

### ISSUE THREAD

**Issue by g-arjones** [rock-core/vscode-rock#10]
In case the user has more specific configurations/setup he/she would be able to create custom debugging launchers in launch.json and still get the extension to take care of boilerplate stuff

**Comment by doudou** [comment]
I think we should get rid of the current way to do debug, and integrate with the normal launch/debug mechanisms for all packages (e.g. C++ and Ruby minitest runs as well)

**Comment by g-arjones** [comment]
You mean expect the user to write launch.json for every package he/she wants to debug?

**Comment by doudou** [comment]
I mean the plugin providing its launch configurations so that it (1) can be edited and (2) they're listed in the debug menu, instead of having our own mechanism.

**Comment by g-arjones** [comment]
> (2) they're listed in the debug menu, instead of having our own mechanism.

This would be ideal, unfortunately I don't think it is possible.
