### ISSUE TITLE
should we replace the implicit "current package" pick by  a list of opened packages, listing the "current" package as first ?

### ISSUE THREAD

**Issue by doudou** [rock-core/vscode-rock#33]
I more often than not end up in files that are not in the package I'm truly working with, and then end up trying a command, finding out it's not doing what I want it to do, undo / cancel, open a file and try again. Being able to pick the package in the generator command(s) would really help there (and would be in line with VSCode's own behavior)

We can either list the "current" package first, or have a "Current Package" entry

The most common situation where I end up doing this (which, in my case is very common) is:
- get a bug report / find a bug in a package I'm not working on
- open said package
- generate launch entry

Right now, I always need to open a file first.

**Comment by g-arjones** [comment]
That is what `rock.packageSelectionMode == "manual"` was for.. But I agree this is an anti-pattern in vscode's natural workflow. I think that the whole "package selection" mechanism is probably going away when we have orogen's debug provider ready. There is also vscode's own `showWorkspaceFolderPick(...)`
