### ISSUE TITLE
create a `rock: Add Package to Workspace` command

### ISSUE THREAD

**Issue by doudou** [rock-core/vscode-rock#35]
Just in the last week, this would have saved me a lot of pain and suffering.

Allow the user to add a package in the workspace by picking it in a list. We would either look at the workspaces that are already opened. So, one must already have at least one package in its workspace, but I don't think it's a bad thing.

**Comment by g-arjones** [comment]
I don't think I understand this one.. You mean showing a quick pick ui with all orogen/cmake/autotools/ruby packages defined in the installation manifest?

**Comment by doudou** [comment]
> You mean showing a quick pick ui with all orogen/cmake/autotools/ruby packages defined in the installation manifest?

Yes, and add the selected package to the workspace.

**Comment by g-arjones** [comment]
I like the idea... Should we filter supported packages (configuration/ruby/orogen/cmake/autotools)?

**Comment by doudou** [comment]
> should we filter supported packages (configuration/ruby/orogen/cmake/autotools)?

I wouldn't. Any package in the installation manifest should do.

**Comment by g-arjones** [comment]
There was [020e4d](https://github.com/Microsoft/vscode/commit/020e4dcac46557b557ee069dba036466706e8f0d) but it was removed.. We should probably watch Microsoft/vscode#35407

**Comment by g-arjones** [comment]
For the record: Microsoft/vscode#42026

**Comment by doudou** [comment]
It got published in vscode 1.20, but unfortunately only as a "proposed API", which means that one cannot use it if running "main" vscode (you need either a special flag or running code insiders)
