### ISSUE TITLE
Update description

### ISSUE THREAD

**Issue by maxehrhardt** [rock-core/vscode-rock#64]
The version that is described in the README (0.5.0) is not the one that is installed, when using VSCode Marketplace (0.4.0). I had to manually install the .vsix provided here.

An update in the description of the package could help to avoid confusion.

Thanks for working on this tool

**Comment by doudou** [comment]
Hey. Good point. Thanks.

Unfortunately, I don't see a way to make it clear that the README on github describes the master version and the readme on the vscode marketplace is the released version. The latter ultimately comes from the former ...

Suggestions ?

**Comment by maxehrhardt** [comment]
Hey,

maybe you could add a text on top of the README that says:

Version provided by VSCode Marketplace(release) can differ from newest version on Github(master). So check to use the right documentation for your installed version.

**Comment by doudou** [comment]
Done
