### ISSUE TITLE
orogen debugging configuration no longer works

### ISSUE THREAD

**Issue by g-arjones** [rock-core/vscode-rock#73]
Apparently, overriding the "type" member is not allowed anymore

**Comment by doudou** [comment]
Oh crap.

**Comment by g-arjones** [comment]
> Oh crap.

Yes. My thoughts exactly.

**Comment by g-arjones** [comment]
[May, 2020 release notes](https://code.visualstudio.com/updates/v1_46#_automatic-debug-configurations-improvements) mention "automatic debug configurations". It seems like generating a launch.json is not necessary anymore, the user only needs one if he/she wishes to tune/modify targets that are automatically generated by the extension (much like how the tasks API works). Sounds cool.

**Comment by doudou** [comment]
Actually, I just debugged an orogen component. I start it with VSCode (didn't try to attach)

**Comment by g-arjones** [comment]
Interesting... it didn't for me (was starting with vscode as well). I will try again later. What version are you on?

**Comment by doudou** [comment]
1.47.0

**Comment by doudou** [comment]
I'm closing this, I've been debugging orogen components in the last few months, and can vouch it works. Feel free to reopen if you still have the problem.
