### ISSUE TITLE
create folder configurations when the package is added to the workspace

### ISSUE THREAD

**Issue by g-arjones** [rock-core/vscode-rock#9]
The only one I can think of right now is cpp_properties.json (to properly set include paths and compile_commands) because the C++ extension does not allow to set them globally.

**Comment by doudou** [comment]
Why a specific command instead of doing it automatically ?

**Comment by g-arjones** [comment]
To make it optional...

**Comment by doudou** [comment]
> To make it optional...

I would rather make it automatic by default and add a configuration flag. I have the impression that this is more "the vscode way". Rather not pollute the command palette too much.

The *vast* majority of people will want to have the `compile_commands` path set properly by default.

**Comment by g-arjones** [comment]
Sounds good to me
